### ISSUE TITLE
Better name?

### ISSUE THREAD

**Issue by LiamDawe** [theCalcaholic/streamdeck#1]
Since the Stream Deck is already a real product, might want to think of a better less conflicting name?

**Comment by allaeddineomc** [comment]
what about "deck streamer"

**Comment by theCalcaholic** [comment]
I just looked it up as I had never heard of it before and it seems more like it's a product category than a product, or did I get that wrong? 

Do you really think that's an issue? It's very hard to find a good name that's not already associated with *something*.  :D

**Comment by AlexandreBonneau** [comment]
It definitely is an existing product.
@allaeddineomc proposition is on point, and can't be found on the web for now.

Better change the project and repo name as soon as possible before gaining public traction :)

**Comment by theCalcaholic** [comment]
I've been thinking about renaming the app to "Steam Portals".
The "deck" in Deck Streamer is too generic for my taste (most people wouldn't know that it is referring to the Steam Deck) and the reference to steam is more important in my opinion (the app works outside of the Steam Deck, but not without Steam).

What do you think of this name? :)

**Comment by AlexandreBonneau** [comment]
"Steam portals" may sound great, but it ought to be too close to Valve's Portal game name..
But first things first; what does this project do exactly? From the features proposed or envisioned, a name would be easier to find in my opinion.

**Comment by theCalcaholic** [comment]
@AlexandreBonneau I don't think, there is a big risk of mixing up "Steam Portals" with the game Portal, as this is not a game. It's an application that let's you add web pages to Steam (as "non-steam games") in a way that integrates nicely with Big Picture/Steam Deck.
It's main use case is adding streaming sites like Netflix or Youtube to the Steam Deck UI

**Comment by AlexandreBonneau** [comment]
What about `Web deck`?

**Comment by theCalcaholic** [comment]
@AlexandreBonneau see above:
> The "deck" in Deck Streamer is too generic for my taste (most people wouldn't know that it is referring to the Steam Deck) and the reference to steam is more important in my opinion (the app works outside of the Steam Deck, but not without Steam).

**Comment by theCalcaholic** [comment]
Actually, I think I'll go with Steam Portals. I like the sound of it and I think it represents what the application does quite well (integrating external services into steam).

Thanks everyone for your input!
